/*CREATE PROFILES TO CHECK EVERY OUTCOME. THIS IS BETTER THAN PROC PRINT BECAUSE PROC PRINT ONLY SHOWS SOME PROFILES*/
proc freq data= derived.adherence_cat;
   tables NEG_ADHERE*CVX_STAT*VLV_STAT*VIA_PER*SCJ_SEEN*VIA_IMP*NO_RX/list missing nocum nopercent;
run;
