/*TEST IF VARIABLES ARE KEY FIELDS*/

/*DUPOUT SHOWS WHAT WAS DELETED	*/
/*OUT SHOWS WHAT WAS KEPT*/

/*DUPLICATES IS EMPTY, THEN THE VARIABLES IN THE BY STATEMENT ARE*/
/*THE KEY FIELDS (THEY MAKE A ROW UNIQUE)*/


proc sort data=DSN dupout=duplicate_obs nodupkey out=unique_obs; 
	by vars;
run;
